# world setting
json_dir: ../../HouseExpo/json/
map_id_set: ../../HouseExpo/dataset.txt
meter2pixel: 16 # X pixel =1 meter
mode: 0  # 0 for exploration mode, 1 for navigation mode

obstacle:
  number: 0 # number of obstacle added to the world
  size: # size of obstacle added in meter, radius/half length
    min: 1
    max: 5

# robot setting
robotRadius: 0 # robot radius in meter
stepLength:
  linear: 6 # robot linear movement in each step in meter
  angular: 30 # robot angular movement in each step in degree
startPose: # robot starting pose [y;x;theta] in meter in world coord with center as origin | theta: angle to the x-axis
  x: 0
  y: 0
  theta: 0
resetRandomPose: 0 # flag of whether randomly set robot init pose ar each reset | if 0, robot reset to startPose at each reset

# laser setting
laser:
  range: 15 # laser range in meter
  fov: 360 # laser field of view in degree
  resolution: 1 # laser rotation resolution in degree
  noiseSigma: 0.2 # sigma of Gaussian distribution of laser noise

# slam setting
slamError:
  linear: 0.1 # slam linear registration error in pixel
  angular: 5 # slam rotational registration error in degree
  
# state setting
stateSize: # state size in meter
  x: 4 # state in pixel = x * meter2pixel
  y: 4
